server:
  port: 8095

spring:
  application:
    name: patrubki-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: substitute
